In [132]:
import pandas as pd
import numpy as np


df = pd.read_csv("C:/Users/Youcode/Desktop/DEV Ai/DataStore360/data/RAW/store_data.csv", encoding="latin-1")
df_clean =  df.copy()

In [134]:
#deleting duplicated

df_clean = df_clean.drop_duplicates()

In [135]:
#saving
df_clean.to_csv('../data/processed/store_data.csv')

In [136]:
#duplicated row id
df_clean["Row ID"].duplicated().sum()

df_clean['Row ID'] = range(1, len(df_clean)+1)

In [137]:
#fixing dates //coerce :if pandas cant interpret a value as date  it change it to Nat
df_clean['Order Date'] = pd.to_datetime(df_clean['Order Date'], format='mixed', errors='coerce')

df_clean['Ship Date'] = pd.to_datetime(df_clean['Ship Date'] , format='mixed' , errors='coerce')

In [190]:
#fixing the ship days
df_clean['shipping days'] = (df_clean['Ship Date'] - df_clean['Order Date']).dt.days

invalid_dates = df_clean["Ship Date"] < df_clean["Order Date"]
df_valid_dates = df_clean[~invalid_dates].copy()

avg_shipping = df_valid_dates.groupby('Ship Mode')['shipping days'].mean().apply(np.floor).sort_values()

avg_shipping
# df_clean.loc[9101, 'Ship Mode'] = 'Same Day'
# df_clean.loc[10033, 'Ship Mode'] = 'Same Day'

df_clean[invalid_dates][["Order ID","Order Date","Ship Date",'Ship Mode']]



# df_clean[invalid_dates]['Ship Date'] = df_clean['Order Date'] + pd.to_timedelta(avg_shipping[df_clean['Ship Mode']], unit="D")


# df_clean.loc[invalid_dates, 'Ship Date'] = (df_clean.loc[invalid_dates, 'Order Date'] + 
#                                             pd.to_timedelta(
#                                                 df_clean.loc[invalid_dates, 'Ship Mode'].map(avg_shipping),
#                                                 unit="D"
#                                                 )
#                                             )

# df_clean.groupby('Order ID').sum()

# df_clean.loc[9101, ['Order Date','Ship Date']]


# df_clean[
#         df_clean["Ship Mode"].isna() & invalid_dates
#     ].groupby('Order ID')[['Order ID','Order Date','Ship Date','Ship Mode']].value_counts().sort_values(ascending=False)



# df_clean[
#     df_clean["Ship Mode"].isna() & invalid_dates
# ].groupby("Order ID")[
#     ["Order ID", "Order Date", "Ship Date", "Ship Mode"]
# ].value_counts(dropna=False).sort_values(ascending=False)

             Order ID Order Date  Ship Date       Ship Mode
1562   US-2017-102890 2017-06-30 2010-01-01        Same Day
2517   CA-2017-123134 2017-05-02 2010-01-01  Standard Class
3279   CA-2014-102988 2014-04-05 2010-01-01    Second Class
4939   CA-2014-157147 2014-01-13 2010-01-01  Standard Class
7099   CA-2015-124933 2015-12-26 2010-01-01    Second Class
9101   CA-2015-163181 2015-11-07 2010-01-01             NaN
10010  CA-2016-154767 2016-06-28 2010-01-01    Second Class
10033  CA-2017-110310 2017-10-27 2010-01-01             NaN

In [187]:
df_clean[df_clean['Order ID'] == "CA-2017-110310"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,shipping days
9239,9240,CA-2017-110310,2017-10-27,2017-11-02,NaN,NB-18655,NaN,Corporate,United States,Tallahassee,...,South,OFF-PA-10001685,Office Supplies,Paper,Easy-staple paper,56.784,7.0,0.2,20.5842,6.0
9240,9241,CA-2017-110310,2017-10-27,2017-11-02,Standard Class,NB-18655,Nona Balk,Corporate,United States,Tallahassee,...,South,OFF-BI-10001097,Office Supplies,Binders,Avery Hole Reinforcements,5.607,3.0,0.7,-3.9249,6.0
9241,9242,CA-2017-110310,2017-10-27,2017-11-02,Standard Class,NB-18655,Nona Balk,Corporate,United States,Tallahassee,...,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,6.576,3.0,0.2,0.5754,6.0
10033,10009,CA-2017-110310,2017-10-27,2010-01-01,NaN,NB-18655,NaN,Corporate,United States,Tallahassee,...,South,OFF-PA-10001685,Office Supplies,Paper,Easy-staple paper,56.784,7.0,0.2,20.5842,-2856.0